# Generated by Django 6.0.2 on 2026-04-05 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlertasInasistencia',
            fields=[
                ('id_alerta', models.AutoField(db_comment='Clave primaria. Identificador de la alerta.\n', primary_key=True, serialize=False)),
                ('aprendiz_id', models.IntegerField(db_comment='Llave forßnea. Relaciona la alerta con el aprendiz.\n')),
                ('cantidad_fallas', models.IntegerField(db_comment='N·mero acumulado de inasistencias.\n')),
                ('fecha_alerta', models.DateTimeField(db_comment='Fecha de generaci¾n de la alerta.\n')),
                ('mensaje', models.TextField(db_comment='Descripci¾n o detalle de la alerta.\n')),
            ],
            options={
                'db_table': 'alertas_inasistencia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ambiente',
            fields=[
                ('id_ambiente', models.IntegerField(db_comment='Clave primaria. Identificador ·nico del ambiente.\n', primary_key=True, serialize=False)),
                ('num_ambiente', models.SmallIntegerField(db_comment='N·mero o c¾digo del ambiente fÝsico.\n')),
                ('capacidad', models.SmallIntegerField(db_comment='Cantidad de personas que pueden estar en un ambiente')),
                ('tipo_ambiente', models.CharField(db_comment='Tipo del ambiente (auditorio, sala, aula, etc.).\n', max_length=45)),
                ('estado', models.CharField(db_comment='Estado actual del ambiente (disponible, ocupado, mantenimiento, etc.).\n', max_length=30)),
            ],
            options={
                'db_table': 'ambiente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Coordinacion',
            fields=[
                ('id_coordinacion', models.AutoField(db_comment='Clave primaria. Identificador de la coordinaci¾n.\n', primary_key=True, serialize=False)),
                ('nombre_coordinacion', models.CharField(db_comment='Nombre de la coordinaci¾n (ej. tecnologia e innovacion).\n', max_length=45)),
                ('correo_coordinacion', models.CharField(db_comment='Correo electr¾nico institucional de la coordinaci¾n.\n\n', max_length=30)),
            ],
            options={
                'db_table': 'coordinacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DataWizardIdentifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serializer', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('field', models.CharField(blank=True, max_length=255, null=True)),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
                ('attr_id', models.PositiveIntegerField(blank=True, null=True)),
                ('resolved', models.IntegerField()),
                ('attr_field', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'data_wizard_identifier',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DataWizardRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10)),
                ('header_col', models.IntegerField()),
                ('start_col', models.IntegerField()),
                ('end_col', models.IntegerField(blank=True, null=True)),
                ('header_row', models.IntegerField()),
                ('start_row', models.IntegerField()),
                ('end_row', models.IntegerField(blank=True, null=True)),
                ('count', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'data_wizard_range',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DataWizardRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('row', models.PositiveIntegerField()),
                ('success', models.IntegerField()),
                ('fail_reason', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'data_wizard_record',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DataWizardRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_count', models.IntegerField(blank=True, null=True)),
                ('loader', models.CharField(blank=True, max_length=255, null=True)),
                ('serializer', models.CharField(blank=True, max_length=255, null=True)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'data_wizard_run',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DataWizardRunlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
            ],
            options={
                'db_table': 'data_wizard_runlog',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricoIncidentes',
            fields=[
                ('id_historico', models.AutoField(db_comment='Clave primaria. Identificador del historial del incidente.\n', primary_key=True, serialize=False)),
                ('descripcion', models.TextField(blank=True, db_comment='Descripci¾n de los hechos o seguimiento.\n', null=True)),
                ('fecha_registro', models.DateTimeField(db_comment='Fecha del registro en el historial.\n\n')),
            ],
            options={
                'db_table': 'historico_incidentes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Jornada',
            fields=[
                ('id_jornada', models.IntegerField(db_comment='Clave primaria. Identificador de la jornada.\n', primary_key=True, serialize=False)),
                ('nombre_jornada', models.CharField(db_comment='Nombre de la jornada (ma±ana, tarde, noche).\n\n', max_length=9)),
            ],
            options={
                'db_table': 'jornada',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Modalidad',
            fields=[
                ('id_modalidad', models.IntegerField(db_comment='Clave primaria. Identificador de la modalidad.\n', primary_key=True, serialize=False)),
                ('nombre_modalidad', models.CharField(db_comment='Nombre de la modalidad (presencial, sincronica).\n\n', max_length=10)),
            ],
            options={
                'db_table': 'modalidad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Programas',
            fields=[
                ('id_programas', models.IntegerField(db_comment='Clave primaria. Identificador del programa acadÚmico.\n', primary_key=True, serialize=False)),
                ('nombre_programa', models.CharField(db_comment='Nombre del programa.\n', max_length=50)),
                ('nivel_formacion', models.CharField(db_comment='Nivel de formaci¾n (tecn¾logo, tÚcnico, etc.).\n', max_length=30)),
                ('duracion', models.CharField(db_comment='Duraci¾n estimada del programa.\n', max_length=50)),
            ],
            options={
                'db_table': 'programas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Recursos',
            fields=[
                ('id_recurso', models.AutoField(db_comment='Clave primaria. Identificador del recurso.\n', primary_key=True, serialize=False)),
                ('serial_recurso', models.CharField(db_comment='Serial fÝsico o interno del recurso.\n', max_length=100)),
                ('num_recurso', models.IntegerField(db_comment='Nombre del recurso en el ambiente.\n')),
                ('nombre_recurso', models.CharField(db_comment='Nombre del recurso.\n', max_length=60)),
                ('estado', models.CharField(blank=True, db_comment='Estado del recurso (operativo, da±ado, en mantenimiento).\n', max_length=16, null=True)),
                ('observacion', models.TextField(blank=True, db_comment='Observacion hacia algun recurso.', null=True)),
            ],
            options={
                'db_table': 'recursos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RegistroInasistencia',
            fields=[
                ('id_inasistencia', models.AutoField(db_comment='Clave primaria. Identificador del registro.\n', primary_key=True, serialize=False)),
                ('fecha_inasistencia', models.DateField(db_comment='Fecha del registro de asistencia.\n')),
                ('estado_inasistencia', models.CharField(db_comment='Estado: S (asisti¾), R (retraso), N (no asistio).\n', max_length=1)),
                ('jornada', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='LoginApp.jornada')),
                ('aprendiz_usuario_id_usuario', models.ForeignKey(db_column='aprendiz_Usuario_id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, to='LoginApp.aprendiz')),
                ('instructor_usuario_id_usuario', models.ForeignKey(db_column='instructor_Usuario_id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, to='LoginApp.instructor')),
                ('tipo_inasistencia', models.CharField(blank=True, choices=[('Justificada', 'Justificada'), ('No justificada', 'No justificada')], max_length=20, null=True)),
            ],
            options={
                'db_table': 'registro_inasistencia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RegistroIncidente',
            fields=[
                ('id_incidente', models.AutoField(db_comment='Clave primaria. Identificador del incidente.\n\n', primary_key=True, serialize=False)),
                ('descripcion', models.TextField(blank=True, db_comment='Descripci¾n general del incidente.\n', null=True)),
                ('fecha_incidente', models.DateField(db_comment='Fecha en que ocurri¾.\n')),
                ('hora_incidente', models.TimeField(db_comment='Hora en que ocurrio.')),
                ('ambiente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='LoginApp.ambiente')),
                ('tipo_inc', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='LoginApp.tipoincidente')),
                ('nivel_gravedad', models.CharField(blank=True, choices=[('Bajo', 'Bajo'), ('Medio', 'Medio'), ('Alto', 'Alto')], max_length=10, null=True)),
                ('usuario_id_usuario', models.ForeignKey(db_column='usuario_id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, to='LoginApp.usuario')),
                ('estado', models.CharField(choices=[('Abierto', 'Abierto'), ('En Proceso', 'En Proceso'), ('Cerrado', 'Cerrado')], default='Abierto', max_length=20)),
            ],
            options={
                'db_table': 'registro_incidente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RegistroMinuta',
            fields=[
                ('id_minuta', models.AutoField(db_comment='Clave primaria. Identificador del registro de minuta.\n', primary_key=True, serialize=False)),
                ('fecha_hora_recibo', models.DateTimeField(db_comment='Fecha y hora de recibo del ambiente.\n')),
                ('fecha_hora_entrega', models.DateTimeField(db_comment='Fecha y hora de entrega.\n')),
                ('novedad', models.TextField(blank=True, db_comment='Novedad o eventualidad ocurrida.\n', null=True)),
                ('descripcion_min', models.TextField(blank=True, db_comment='Observaciones generales.\n', null=True)),
                ('estado', models.TextField(db_comment='Estado general del ambiente al momento.\n')),
                ('registro_minutacol', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'registro_minuta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.IntegerField(db_comment='Clave primaria. Identificador del rol.\n', primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(db_comment='Nombre del rol (aprendiz, instructor, etc.).\n\n', max_length=45)),
            ],
            options={
                'db_table': 'rol',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SourcesFilesource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('file', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
            ],
            options={
                'db_table': 'sources_filesource',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SourcesUrlsource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
            ],
            options={
                'db_table': 'sources_urlsource',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoIncidente',
            fields=[
                ('id_tipo_inc', models.IntegerField(db_comment='Clave primaria. Identificador del tipo de incidente.\n', primary_key=True, serialize=False)),
                ('tipo_incidente', models.CharField(db_comment='Nombre del tipo.\n', max_length=45)),
                ('observacion_inc', models.TextField(db_comment='Observaci¾n adicional.\n\n')),
            ],
            options={
                'db_table': 'tipo_incidente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoRecurso',
            fields=[
                ('id_tipo_recurso', models.IntegerField(db_comment='Clave primaria. Identificador del tipo de recurso.\n', primary_key=True, serialize=False)),
                ('recurso_tipo', models.CharField(db_comment='Nombre del tipo (ej. PC, proyector, aire, etc.).\n', max_length=45)),
                ('descripcion_tipo', models.CharField(blank=True, db_comment='Descripci¾n adicional.\n\n', max_length=60, null=True)),
            ],
            options={
                'db_table': 'tipo_recurso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TrasladoRecurso',
            fields=[
                ('id_traslado', models.AutoField(db_comment='Clave primaria. Identificador del traslado.\n', primary_key=True, serialize=False)),
                ('ambiente_destino', models.IntegerField(db_comment='Ambiente de destino.\n')),
                ('fecha_traslado', models.DateTimeField(db_comment='Fecha del traslado.\n')),
                ('observacion', models.TextField(blank=True, db_comment='Observaciones del traslado.\n\n', null=True)),
            ],
            options={
                'db_table': 'traslado_recurso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(db_comment='Clave primaria. Identificador del usuario.\n', primary_key=True, serialize=False)),
                ('p_nombre', models.CharField(db_comment='Primer nombre.\n', max_length=50)),
                ('s_nombre', models.CharField(blank=True, db_comment='Segundo nombre.\n', max_length=50, null=True)),
                ('p_apellido', models.CharField(db_comment='Primer apellido.\n', max_length=45)),
                ('s_apellido', models.CharField(blank=True, db_comment='Segundo apellido.\n', max_length=45, null=True)),
                ('tipo_documento', models.CharField(db_comment='Tipo de documento.\n', max_length=4)),
                ('num_documento', models.IntegerField(db_comment='N·mero de documento.\n')),
                ('correo', models.CharField(db_comment='Correo institucional.\n', max_length=100)),
                ('contrasena', models.CharField(db_column='Contraseña', max_length=100)),
            ],
            options={
                'db_table': 'usuario',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('idficha', models.AutoField(primary_key=True, serialize=False)),
                ('num_ficha', models.IntegerField(db_column='Num_ficha', unique=True)),
            ],
            options={
                'db_table': 'ficha',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='GuardaSeguridad',
            fields=[
                ('usuario_id_usuario', models.OneToOneField(db_column='Usuario_id_usuario', db_comment='Clave primaria y forßnea. Usuario que cumple funciones de guarda de seguridad.\n', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='LoginApp.usuario')),
                ('turno', models.CharField(db_comment='Turno del guarda(ej. ma±ana, tarde, etc...)', max_length=6)),
                ('fecha_ingreso', models.DateField(db_comment='Fecha de ingreso laboral del guarda.\n')),
                ('estado', models.CharField(db_comment='Estado laboral del guarda (activo/inactivo).\n\n', max_length=8)),
            ],
            options={
                'db_table': 'guarda_seguridad',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserRol',
            fields=[
                ('id_user_rol', models.AutoField(db_comment='Clave primaria. Identificador del registro.\n', primary_key=True, serialize=False)),
                ('id_rol', models.ForeignKey(blank=True, db_column='id_rol', db_comment='Rol asignado al usuario.\n\n', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='LoginApp.rol')),
                ('id_usuario', models.ForeignKey(blank=True, db_column='id_usuario', db_comment='Usuario asociado.\n', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='LoginApp.usuario')),
            ],
            options={
                'db_table': 'user_rol',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Aprendiz',
            fields=[
                ('usuario_id_usuario', models.OneToOneField(db_column='Usuario_id_usuario', db_comment='Llave primaria y forßnea. Identificador del aprendiz (usuario base).\n', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='LoginApp.usuario')),
                ('ficha_idficha', models.ForeignKey(blank=True, db_column='ficha_idficha', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='LoginApp.ficha')),
                ('programas_id_programas', models.ForeignKey(blank=True, db_column='programas_id_programas', db_comment='Llave forßnea. Programa de formaci¾n del aprendiz.\n', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='LoginApp.programas')),
            ],
            options={
                'db_table': 'aprendiz',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Coordinador',
            fields=[
                ('usuario_id_usuario', models.OneToOneField(db_column='Usuario_id_usuario', db_comment='Llave primaria y forßnea. Usuario que tiene el rol de coordinador.\n', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='LoginApp.usuario')),
                ('coordinacion_id_coordinacion', models.ForeignKey(blank=True, db_column='coordinacion_id_coordinacion', db_comment='Llave forßnea. Relaciona con la coordinaci¾n que lidera.\n\n', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='LoginApp.coordinacion')),
            ],
            options={
                'db_table': 'coordinador',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('usuario_id_usuario', models.OneToOneField(db_column='Usuario_id_usuario', db_comment='Llave primaria y forßnea. Usuario que act·a como instructor.\n', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='LoginApp.usuario')),
                ('email', models.CharField(db_comment='Correo electr¾nico institucional.\n', max_length=100)),
                ('telefono', models.CharField(db_comment='TelÚfono de contacto.\n', max_length=20)),
                ('estado', models.CharField(db_comment='Estado laboral (activo, inactivo).\n', max_length=8)),
                ('coordinacion_id_coordinacion', models.ForeignKey(blank=True, db_column='coordinacion_id_coordinacion', db_comment='Coordinaci¾n a la que pertenece.\n', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='LoginApp.coordinacion')),
            ],
            options={
                'db_table': 'instructor',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='ficha',
            name='instructores',
            field=models.ManyToManyField(db_table='ficha_instructor', related_name='fichas', to='LoginApp.instructor'),
        ),
    ]
