# Generated by Django 6.0.2 on 2026-04-05 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ficha',
            name='instructores',
        ),
        migrations.AddField(
            model_name='ficha',
            name='instructor_usuario_id_usuario',
            field=models.ForeignKey(blank=True, db_column='instructor_Usuario_id_usuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fichas', to='LoginApp.instructor'),
        ),
    ]
