# Generated by Django 6.0.2 on 2026-06-10 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginApp', '0002_revert_to_original'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registroinasistencia',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='registroincidente',
            options={'managed': True},
        ),
        migrations.AlterField(
            model_name='aprendiz',
            name='programas_id_programas',
            field=models.ForeignKey(blank=True, db_column='programas_id_programas', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='LoginApp.programas'),
        ),
        migrations.AlterField(
            model_name='aprendiz',
            name='usuario_id_usuario',
            field=models.OneToOneField(db_column='Usuario_id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='LoginApp.usuario'),
        ),
        migrations.AlterField(
            model_name='coordinador',
            name='coordinacion_id_coordinacion',
            field=models.ForeignKey(blank=True, db_column='coordinacion_id_coordinacion', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='LoginApp.coordinacion'),
        ),
        migrations.AlterField(
            model_name='coordinador',
            name='usuario_id_usuario',
            field=models.OneToOneField(db_column='Usuario_id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='LoginApp.usuario'),
        ),
        migrations.AlterField(
            model_name='guardaseguridad',
            name='estado',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='guardaseguridad',
            name='fecha_ingreso',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='guardaseguridad',
            name='turno',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='guardaseguridad',
            name='usuario_id_usuario',
            field=models.OneToOneField(db_column='Usuario_id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='LoginApp.usuario'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='coordinacion_id_coordinacion',
            field=models.ForeignKey(blank=True, db_column='coordinacion_id_coordinacion', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='LoginApp.coordinacion'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='estado',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='telefono',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='usuario_id_usuario',
            field=models.OneToOneField(db_column='Usuario_id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='LoginApp.usuario'),
        ),
        migrations.AlterField(
            model_name='userrol',
            name='id_rol',
            field=models.ForeignKey(blank=True, db_column='id_rol', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='LoginApp.rol'),
        ),
        migrations.AlterField(
            model_name='userrol',
            name='id_user_rol',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userrol',
            name='id_usuario',
            field=models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='LoginApp.usuario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='correo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id_usuario',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='num_documento',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='p_apellido',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='p_nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='s_apellido',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='s_nombre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_documento',
            field=models.CharField(max_length=4),
        ),
        migrations.CreateModel(
            name='AsignacionAmbiente',
            fields=[
                ('id_asignacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('trimestre', models.CharField(max_length=50)),
                ('estado', models.CharField(default='ACTIVO', max_length=20)),
                ('ambiente', models.ForeignKey(db_column='ambiente_id', on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='LoginApp.ambiente')),
                ('instructor', models.ForeignKey(db_column='instructor_Usuario_id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='LoginApp.instructor')),
            ],
            options={
                'db_table': 'asignacion_ambiente',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Justificacion',
            fields=[
                ('id_justificacion', models.AutoField(primary_key=True, serialize=False)),
                ('pdf_file', models.FileField(db_column='archivo_pdf', upload_to='justificaciones/')),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobada', 'Aprobada'), ('Rechazada', 'Rechazada')], default='Pendiente', max_length=20)),
                ('observacion', models.TextField(blank=True, db_column='descripcion', null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('inasistencia', models.OneToOneField(db_column='registro_inasistencia_id', on_delete=django.db.models.deletion.CASCADE, related_name='justificacion', to='LoginApp.registroinasistencia')),
            ],
            options={
                'db_table': 'justificacion',
                'managed': True,
            },
        ),
    ]
