# Generated by Django 6.0.2 on 2026-06-15 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginApp', '0003_add_estado_tipo_asignacion_justificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacionambiente',
            name='jornada',
            field=models.ForeignKey(blank=True, db_column='jornada_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='asignaciones', to='LoginApp.jornada'),
        ),
        migrations.AlterField(
            model_name='justificacion',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobada', 'Aprobada'), ('Rechazada', 'Rechazada')], db_column='estado', default='Pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='registroinasistencia',
            name='estado_inasistencia',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='registroinasistencia',
            name='fecha_inasistencia',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='registroinasistencia',
            name='id_inasistencia',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='registroincidente',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registroincidente',
            name='fecha_incidente',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='registroincidente',
            name='hora_incidente',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='registroincidente',
            name='id_incidente',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddConstraint(
            model_name='asignacionambiente',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'ACTIVO')), fields=('ambiente', 'jornada', 'fecha_inicio', 'fecha_fin', 'estado'), name='unique_ambiente_jornada_periodo_activo'),
        ),
    ]
