# Generated by Django 6.0.2 on 2026-06-15 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginApp', '0004_asignacionambiente_jornada_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MantenimientoAmbiente',
            fields=[
                ('id_mantenimiento', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion_falla', models.TextField()),
                ('fecha_inicio', models.DateField(auto_now_add=True)),
                ('fecha_estimada_entrega', models.DateField(blank=True, null=True)),
                ('estado_mantenimiento', models.CharField(choices=[('En Curso', 'En Curso'), ('Completado', 'Completado')], default='En Curso', max_length=20)),
                ('diagnostico_reparacion', models.TextField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mantenimiento_ambiente',
                'managed': True,
            },
        ),
        migrations.RemoveConstraint(
            model_name='asignacionambiente',
            name='unique_ambiente_jornada_periodo_activo',
        ),
        migrations.AddField(
            model_name='mantenimientoambiente',
            name='ambiente',
            field=models.ForeignKey(db_column='ambiente_id', on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos', to='LoginApp.ambiente'),
        ),
        migrations.AddField(
            model_name='mantenimientoambiente',
            name='incidente',
            field=models.ForeignKey(blank=True, db_column='incidente_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mantenimientos', to='LoginApp.registroincidente'),
        ),
    ]
