# Generated by Django 6.0.2 on 2026-06-15 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LoginApp', '0005_mantenimientoambiente_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MantenimientoAmbiente',
        ),
    ]
