# Generated by Django 6.0.2 on 2026-06-15 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LoginApp', '0006_delete_mantenimientoambiente'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trasladorecurso',
            options={'managed': True},
        ),
    ]
