# Generated by Django 6.0.2 on 2026-06-15 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginApp', '0007_alter_trasladorecurso_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='trasladorecurso',
            name='instructor_destino',
            field=models.ForeignKey(blank=True, db_column='instructor_destino', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traslados_recibidos', to='LoginApp.instructor'),
        ),
        migrations.AddField(
            model_name='trasladorecurso',
            name='instructor_origen',
            field=models.ForeignKey(blank=True, db_column='instructor_origen', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traslados_autorizados', to='LoginApp.instructor'),
        ),
        migrations.AddField(
            model_name='trasladorecurso',
            name='tiempo_prestamo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
