# Generated by Django 6.0.2 on 2026-06-18 02:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginApp', '0008_trasladorecurso_ambiente_origen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficha',
            name='instructores',
            field=models.ManyToManyField(blank=True, db_table='ficha_instructor', related_name='fichas_asignadas', to='LoginApp.instructor'),
        ),
    ]
