# Generated by Django 6.0.2 on 2026-06-18 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginApp', '0009_ficha_instructores_trasladorecurso_ambiente_origen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trasladorecurso',
            name='ambiente_origen',
            field=models.ForeignKey(blank=True, db_column='ambiente_origen', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='LoginApp.ambiente'),
        ),
        migrations.AddField(
            model_name='trasladorecurso',
            name='recurso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='LoginApp.recursos'),
        ),
        migrations.AlterField(
            model_name='trasladorecurso',
            name='ambiente_destino',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trasladorecurso',
            name='fecha_traslado',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trasladorecurso',
            name='id_traslado',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='trasladorecurso',
            name='observacion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
