# Generated by Django 6.0.2 on 2026-06-18 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LoginApp', '0010_trasladorecurso_ambiente_origen_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ficha',
            name='instructor_usuario_id_usuario',
        ),
    ]
