# Generated by Django 6.0.2 on 2026-06-18 02:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginApp', '0011_remove_ficha_instructor_usuario_id_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trasladorecurso',
            name='ambiente_destino',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='trasladorecurso',
            name='ambiente_origen',
            field=models.ForeignKey(db_column='ambiente_origen', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='LoginApp.ambiente'),
        ),
        migrations.AlterField(
            model_name='trasladorecurso',
            name='fecha_traslado',
            field=models.DateTimeField(default='2026-06-17 00:00:00'),
        ),
        migrations.AlterField(
            model_name='trasladorecurso',
            name='recurso',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='LoginApp.recursos'),
        ),
    ]
