# Generated by Django 6.0.3 on 2026-04-03 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UsuarioApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('usuario', models.OneToOneField(db_column='Usuario_id_usuario', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='instructor', serialize=False, to='UsuarioApp.usuario')),
                ('email', models.EmailField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=8)),
            ],
            options={
                'db_table': 'instructor',
                'managed': False,
            },
        ),
    ]
