-- MySQL Script generated by MySQL Workbench
-- Wed Jun 18 20:00:47 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bdproyectoPrueba
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bdproyectoPrueba
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bdproyectoPrueba` ;
-- -----------------------------------------------------
-- Schema default_schema
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `bdproyectoPrueba` ;

-- -----------------------------------------------------
-- Table `bdproyectoPrueba`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdproyectoPrueba`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `bdproyectoPrueba`.`Usuario` (
  `id_usuario` INT NOT NULL,
  `p_nombre` VARCHAR(50) NULL DEFAULT NULL,
  `s_nombre` VARCHAR(50) NULL DEFAULT NULL,
  `p_apellido` VARCHAR(45) NULL,
  `s_apellido` VARCHAR(45) NULL,
  `tipo_documento` ENUM('T.I', ' C.C', ' C.E', 'Pasaporte') NULL,
  `Num_documento` INT NULL,
  `estado` ENUM('Activo', 'Inactivo') NULL DEFAULT 'Activo',
  PRIMARY KEY (`id_usuario`));


-- -----------------------------------------------------
-- Table `bdproyectoPrueba`.`modalidad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdproyectoPrueba`.`modalidad` ;

CREATE TABLE IF NOT EXISTS `bdproyectoPrueba`.`modalidad` (
  `id_modalidad` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `nombre_modalidad` ENUM('presencial', 'sincronica') NULL DEFAULT NULL,
  PRIMARY KEY (`id_modalidad`));


-- -----------------------------------------------------
-- Table `bdproyectoPrueba`.`jornada`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdproyectoPrueba`.`jornada` ;

CREATE TABLE IF NOT EXISTS `bdproyectoPrueba`.`jornada` (
  `id_jornada` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `nombre_jornada` ENUM('mañana', 'tarde', 'noche', 'madrugada') NULL DEFAULT NULL,
  PRIMARY KEY (`id_jornada`));


-- -----------------------------------------------------
-- Table `bdproyectoPrueba`.`coordinacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdproyectoPrueba`.`coordinacion` ;

CREATE TABLE IF NOT EXISTS `bdproyectoPrueba`.`coordinacion` (
  `id_coordinacion` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `nombre_coordinacion` VARCHAR(50) NULL DEFAULT NULL,
  `correo_cordinacion` VARCHAR(30) NULL DEFAULT NULL,
  PRIMARY KEY (`id_coordinacion`));


-- -----------------------------------------------------
-- Table `bdproyectoPrueba`.`programas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdproyectoPrueba`.`programas` ;

CREATE TABLE IF NOT EXISTS `bdproyectoPrueba`.`programas` (
  `id_programas` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `nombre_programa` VARCHAR(50) NULL DEFAULT NULL,
  `nivel_formacion` VARCHAR(30) NULL DEFAULT NULL,
  `duracion` VARCHAR(50) NULL DEFAULT NULL,
  `jornada_id` INT NULL DEFAULT NULL,
  `modalidad_id` INT NULL DEFAULT NULL,
  `coordinacion_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_programas`),
  CONSTRAINT ``
    FOREIGN KEY (`jornada_id`)
    REFERENCES `bdproyectoPrueba`.`jornada` (`id_jornada`),
  CONSTRAINT ``
    FOREIGN KEY (`modalidad_id`)
    REFERENCES `bdproyectoPrueba`.`modalidad` (`id_modalidad`),
  CONSTRAINT ``
    FOREIGN KEY (`coordinacion_id`)
    REFERENCES `bdproyectoPrueba`.`coordinacion` (`id_coordinacion`));

CREATE INDEX ON `bdproyectoPrueba`.`programas` (`coordinacion_id` ASC) VISIBLE;

CREATE INDEX ON `bdproyectoPrueba`.`programas` (`coordinacion_id` ASC) VISIBLE;

CREATE INDEX ON `bdproyectoPrueba`.`programas` (`coordinacion_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `bdproyectoPrueba`.`aprendiz`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdproyectoPrueba`.`aprendiz` ;

CREATE TABLE IF NOT EXISTS `bdproyectoPrueba`.`aprendiz` (
  `id_aprendiz` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `Usuario_id_usuario` INT NOT NULL,
  `Num_ficha` MEDIUMINT NULL DEFAULT NULL,
  PRIMARY KEY (`id_aprendiz`, `Usuario_id_usuario`),
  CONSTRAINT `fk_aprendiz_Usuario1`
    FOREIGN KEY (`Usuario_id_usuario`)
    REFERENCES `bdproyectoPrueba`.`Usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

CREATE INDEX `fk_aprendiz_Usuario1_idx` ON `bdproyectoPrueba`.`aprendiz` (`Usuario_id_usuario` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `bdproyectoPrueba`.`registro_asistencia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdproyectoPrueba`.`registro_asistencia` ;

CREATE TABLE IF NOT EXISTS `bdproyectoPrueba`.`registro_asistencia` (
  `id_asistencia` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `fecha_asistencia` DATE NULL DEFAULT NULL,
  `estado_asistencia` ENUM('N', 'E', 'S') NULL DEFAULT NULL,
  `jorn_id` INT NULL DEFAULT NULL,
  `apr_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_asistencia`),
  CONSTRAINT ``
    FOREIGN KEY (`jorn_id`)
    REFERENCES `bdproyectoPrueba`.`jornada` (`id_jornada`),
  CONSTRAINT ``
    FOREIGN KEY (`apr_id`)
    REFERENCES `bdproyectoPrueba`.`aprendiz` (`id_aprendiz`));

CREATE INDEX ON `bdproyectoPrueba`.`registro_asistencia` (`apr_id` ASC) VISIBLE;

CREATE INDEX ON `bdproyectoPrueba`.`registro_asistencia` (`apr_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `bdproyectoPrueba`.`ambiente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdproyectoPrueba`.`ambiente` ;

CREATE TABLE IF NOT EXISTS `bdproyectoPrueba`.`ambiente` (
  `id_ambiente` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `num_ambiente` SMALLINT NULL DEFAULT NULL,
  `capacidad` SMALLINT NULL DEFAULT NULL,
  `tipo_ambiente` VARCHAR(50) NULL DEFAULT NULL,
  `estado` VARCHAR(30) NULL DEFAULT NULL,
  `coordinacion_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_ambiente`),
  CONSTRAINT ``
    FOREIGN KEY (`coordinacion_id`)
    REFERENCES `bdproyectoPrueba`.`coordinacion` (`id_coordinacion`));

CREATE INDEX ON `bdproyectoPrueba`.`ambiente` (`coordinacion_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `bdproyectoPrueba`.`tipo_recurso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdproyectoPrueba`.`tipo_recurso` ;

CREATE TABLE IF NOT EXISTS `bdproyectoPrueba`.`tipo_recurso` (
  `id_recurso` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `recurso_tipo` VARCHAR(15) NULL DEFAULT NULL,
  `descripcion` VARCHAR(30) NULL DEFAULT NULL,
  PRIMARY KEY (`id_recurso`));


-- -----------------------------------------------------
-- Table `bdproyectoPrueba`.`recursos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdproyectoPrueba`.`recursos` ;

CREATE TABLE IF NOT EXISTS `bdproyectoPrueba`.`recursos` (
  `serial_recurso` VARCHAR(30) NULL DEFAULT NULL,
  `num_recurso` TINYINT NULL DEFAULT NULL,
  `estado` VARCHAR(20) NULL DEFAULT NULL,
  `observacion` TEXT NULL DEFAULT NULL,
  `ambiente_id` INT NULL DEFAULT NULL,
  `recurso_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`serial_recurso`),
  CONSTRAINT ``
    FOREIGN KEY (`ambiente_id`)
    REFERENCES `bdproyectoPrueba`.`ambiente` (`id_ambiente`),
  CONSTRAINT ``
    FOREIGN KEY (`recurso_id`)
    REFERENCES `bdproyectoPrueba`.`tipo_recurso` (`id_recurso`));

CREATE INDEX ON `bdproyectoPrueba`.`recursos` (`recurso_id` ASC) VISIBLE;

CREATE INDEX ON `bdproyectoPrueba`.`recursos` (`recurso_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `bdproyectoPrueba`.`registro_minuta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdproyectoPrueba`.`registro_minuta` ;

CREATE TABLE IF NOT EXISTS `bdproyectoPrueba`.`registro_minuta` (
  `id_minuta` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `fecha_hora_recibido` DATETIME NULL DEFAULT NULL,
  `fecha_hora_entrega` DATETIME NULL DEFAULT NULL,
  `novedad` TEXT NULL DEFAULT NULL,
  `responsable` VARCHAR(30) NULL DEFAULT NULL,
  `descripcion_amb` TEXT NULL DEFAULT NULL,
  `ambiente_id` INT NULL DEFAULT NULL,
  `docu_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_minuta`),
  CONSTRAINT ``
    FOREIGN KEY (`ambiente_id`)
    REFERENCES `bdproyectoPrueba`.`ambiente` (`id_ambiente`),
  CONSTRAINT ``
    FOREIGN KEY (`docu_id`)
    REFERENCES `bdproyectoPrueba`.`Usuario` (`id_usuario`));

CREATE INDEX ON `bdproyectoPrueba`.`registro_minuta` (`docu_id` ASC) VISIBLE;

CREATE INDEX ON `bdproyectoPrueba`.`registro_minuta` (`docu_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `bdproyectoPrueba`.`tipo_incidente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdproyectoPrueba`.`tipo_incidente` ;

CREATE TABLE IF NOT EXISTS `bdproyectoPrueba`.`tipo_incidente` (
  `id_tipo_inc` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `tipo_incidente` VARCHAR(30) NULL DEFAULT NULL,
  `observacion_inc` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id_tipo_inc`));


-- -----------------------------------------------------
-- Table `bdproyectoPrueba`.`registro_incidente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdproyectoPrueba`.`registro_incidente` ;

CREATE TABLE IF NOT EXISTS `bdproyectoPrueba`.`registro_incidente` (
  `id_incidente` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `descripcion` TEXT NULL DEFAULT NULL,
  `fecha_incidente` DATE NULL DEFAULT NULL,
  `hora_incidente` TIME NULL DEFAULT NULL,
  `ambiente_id` INT NULL DEFAULT NULL,
  `tipo_inc_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_incidente`),
  CONSTRAINT ``
    FOREIGN KEY (`ambiente_id`)
    REFERENCES `bdproyectoPrueba`.`ambiente` (`id_ambiente`),
  CONSTRAINT ``
    FOREIGN KEY (`tipo_inc_id`)
    REFERENCES `bdproyectoPrueba`.`tipo_incidente` (`id_tipo_inc`));

CREATE INDEX ON `bdproyectoPrueba`.`registro_incidente` (`tipo_inc_id` ASC) VISIBLE;

CREATE INDEX ON `bdproyectoPrueba`.`registro_incidente` (`tipo_inc_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `bdproyectoPrueba`.`alertas_inasistencia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdproyectoPrueba`.`alertas_inasistencia` ;

CREATE TABLE IF NOT EXISTS `bdproyectoPrueba`.`alertas_inasistencia` (
  `id_alerta` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `aprendiz_id_aprendiz` INT NOT NULL,
  `cantidad_fallas` INT NULL DEFAULT NULL,
  `fecha_alerta` DATETIME NULL DEFAULT CURRENT_TIMESTAMP(),
  `mensaje` TEXT NULL DEFAULT NULL,
  `aprendiz_Usuario_id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_alerta`),
  CONSTRAINT `fk_alertas_inasistencia_aprendiz1`
    FOREIGN KEY (`aprendiz_id_aprendiz` , `aprendiz_Usuario_id_usuario`)
    REFERENCES `bdproyectoPrueba`.`aprendiz` (`id_aprendiz` , `Usuario_id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

CREATE INDEX `fk_alertas_inasistencia_aprendiz1_idx` ON `bdproyectoPrueba`.`alertas_inasistencia` (`aprendiz_id_aprendiz` ASC, `aprendiz_Usuario_id_usuario` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `bdproyectoPrueba`.`guarda_seguridad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdproyectoPrueba`.`guarda_seguridad` ;

CREATE TABLE IF NOT EXISTS `bdproyectoPrueba`.`guarda_seguridad` (
  `Usuario_id_usuario` INT NOT NULL,
  `id_guarda` INT NULL AUTO_INCREMENT,
  `usua_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`Usuario_id_usuario`, `id_guarda`),
  CONSTRAINT ``
    FOREIGN KEY (`usua_id`)
    REFERENCES `bdproyectoPrueba`.`usuario` (`documento`),
  CONSTRAINT `fk_guarda_seguridad_Usuario1`
    FOREIGN KEY (`Usuario_id_usuario`)
    REFERENCES `bdproyectoPrueba`.`Usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

CREATE INDEX ON `bdproyectoPrueba`.`guarda_seguridad` (`usua_id` ASC) VISIBLE;

CREATE INDEX `fk_guarda_seguridad_Usuario1_idx` ON `bdproyectoPrueba`.`guarda_seguridad` (`Usuario_id_usuario` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `bdproyectoPrueba`.`instructor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdproyectoPrueba`.`instructor` ;

CREATE TABLE IF NOT EXISTS `bdproyectoPrueba`.`instructor` (
  `Usuario_id_usuario` INT NOT NULL,
  `id_instructor` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `email` VARCHAR(100) NOT NULL,
  `telefono` VARCHAR(20) NULL DEFAULT NULL,
  `coordinacion` VARCHAR(100) NOT NULL,
  `especialidad` VARCHAR(100) NULL DEFAULT NULL,
  `fecha_ingreso` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`Usuario_id_usuario`, `id_instructor`),
  CONSTRAINT ``
    FOREIGN KEY ()
    REFERENCES `bdproyectoPrueba`.`usuario` (),
  CONSTRAINT `fk_instructor_Usuario1`
    FOREIGN KEY (`Usuario_id_usuario`)
    REFERENCES `bdproyectoPrueba`.`Usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

CREATE INDEX `fk_instructor_Usuario1_idx` ON `bdproyectoPrueba`.`instructor` (`Usuario_id_usuario` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `p_nombre` VARCHAR(50) NOT NULL,
  `s_nombre` VARCHAR(50) NULL DEFAULT NULL,
  `p_apellido` VARCHAR(45) NOT NULL,
  `s_apellido` VARCHAR(45) NULL DEFAULT NULL,
  `tipo_documento` ENUM('CC', 'TI', 'CE', 'OTRO') NOT NULL,
  `num_documento` INT NOT NULL,
  `correo` VARCHAR(100) NOT NULL,
  `contraseña` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_usuario`));


-- -----------------------------------------------------
-- Table `mydb`.`coordinacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`coordinacion` ;

CREATE TABLE IF NOT EXISTS `mydb`.`coordinacion` (
  `id_coordinacion` INT NOT NULL AUTO_INCREMENT,
  `nombre_coordinacion` VARCHAR(45) NOT NULL,
  `correo_coordinacion` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id_coordinacion`));


-- -----------------------------------------------------
-- Table `bdproyectoPrueba`.`Coordinador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdproyectoPrueba`.`Coordinador` ;

CREATE TABLE IF NOT EXISTS `bdproyectoPrueba`.`Coordinador` (
  `Usuario_id_usuario` INT NOT NULL,
  `coordinacion_id_coordinacion` INT NOT NULL,
  PRIMARY KEY (`Usuario_id_usuario`),
  CONSTRAINT `fk_Coordinador_Usuario1`
    FOREIGN KEY (`Usuario_id_usuario`)
    REFERENCES `mydb`.`Usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Coordinador_coordinacion1`
    FOREIGN KEY (`coordinacion_id_coordinacion`)
    REFERENCES `mydb`.`coordinacion` (`id_coordinacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Coordinador_coordinacion1_idx` ON `bdproyectoPrueba`.`Coordinador` (`coordinacion_id_coordinacion` ASC) VISIBLE;

USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`jornada`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`jornada` ;

CREATE TABLE IF NOT EXISTS `mydb`.`jornada` (
  `id_jornada` INT NOT NULL,
  `nombre_jornada` ENUM('Mañana', 'Tarde', 'Noche') NOT NULL,
  PRIMARY KEY (`id_jornada`));


-- -----------------------------------------------------
-- Table `mydb`.`modalidad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`modalidad` ;

CREATE TABLE IF NOT EXISTS `mydb`.`modalidad` (
  `id_modalidad` INT NOT NULL,
  `nombre_modalidad` ENUM('Presencial', 'Virtual', 'Mixta') NOT NULL,
  PRIMARY KEY (`id_modalidad`));


-- -----------------------------------------------------
-- Table `mydb`.`programas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`programas` ;

CREATE TABLE IF NOT EXISTS `mydb`.`programas` (
  `id_programas` INT NOT NULL,
  `nombre_programa` VARCHAR(50) NOT NULL,
  `nivel_formacion` VARCHAR(30) NOT NULL,
  `duracion` VARCHAR(50) NOT NULL,
  `jornada_id` INT NOT NULL,
  `modalidad_id` INT NOT NULL,
  `coordinacion_id` INT NOT NULL,
  PRIMARY KEY (`id_programas`),
  CONSTRAINT `fk_programas_jornada`
    FOREIGN KEY (`jornada_id`)
    REFERENCES `mydb`.`jornada` (`id_jornada`),
  CONSTRAINT `fk_programas_modalidad`
    FOREIGN KEY (`modalidad_id`)
    REFERENCES `mydb`.`modalidad` (`id_modalidad`),
  CONSTRAINT `fk_programas_coordinacion`
    FOREIGN KEY (`coordinacion_id`)
    REFERENCES `mydb`.`coordinacion` (`id_coordinacion`));

CREATE INDEX `fk_programas_jornada` ON `mydb`.`programas` (`jornada_id` ASC) VISIBLE;

CREATE INDEX `fk_programas_modalidad` ON `mydb`.`programas` (`modalidad_id` ASC) VISIBLE;

CREATE INDEX `fk_programas_coordinacion` ON `mydb`.`programas` (`coordinacion_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`instructor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`instructor` ;

CREATE TABLE IF NOT EXISTS `mydb`.`instructor` (
  `Usuario_id_usuario` INT NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `telefono` VARCHAR(20) NOT NULL,
  `coordinacion` VARCHAR(100) NOT NULL,
  `fichas_asignadas` TEXT NOT NULL,
  `estado` ENUM('Activo', 'Inactivo') NOT NULL,
  `jornada_id_jornada` INT NOT NULL,
  `programas_id_programas` INT NOT NULL,
  PRIMARY KEY (`Usuario_id_usuario`),
  CONSTRAINT `fk_instructor_usuario`
    FOREIGN KEY (`Usuario_id_usuario`)
    REFERENCES `mydb`.`Usuario` (`id_usuario`),
  CONSTRAINT `fk_instructor_jornada1`
    FOREIGN KEY (`jornada_id_jornada`)
    REFERENCES `mydb`.`jornada` (`id_jornada`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_instructor_programas1`
    FOREIGN KEY (`programas_id_programas`)
    REFERENCES `mydb`.`programas` (`id_programas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

CREATE INDEX `fk_instructor_jornada1_idx` ON `mydb`.`instructor` (`jornada_id_jornada` ASC) VISIBLE;

CREATE INDEX `fk_instructor_programas1_idx` ON `mydb`.`instructor` (`programas_id_programas` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`guarda_seguridad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`guarda_seguridad` ;

CREATE TABLE IF NOT EXISTS `mydb`.`guarda_seguridad` (
  `Usuario_id_usuario` INT NOT NULL,
  `turno` ENUM('Mañana', 'Tarde', 'Noche') NOT NULL,
  `fecha_ingreso` DATE NOT NULL,
  `estado` ENUM('Activo', 'Inactivo') NOT NULL,
  PRIMARY KEY (`Usuario_id_usuario`),
  CONSTRAINT `fk_guarda_seguridad_usuario`
    FOREIGN KEY (`Usuario_id_usuario`)
    REFERENCES `mydb`.`Usuario` (`id_usuario`));


-- -----------------------------------------------------
-- Table `mydb`.`aprendiz`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`aprendiz` ;

CREATE TABLE IF NOT EXISTS `mydb`.`aprendiz` (
  `Usuario_id_usuario` INT NOT NULL,
  `Num_ficha` MEDIUMINT NOT NULL,
  `programa_id` INT NOT NULL,
  `programas_id_programas` INT NOT NULL,
  `jornada_id_jornada` INT NOT NULL,
  PRIMARY KEY (`Usuario_id_usuario`),
  CONSTRAINT `fk_aprendiz_programas1`
    FOREIGN KEY (`programas_id_programas`)
    REFERENCES `mydb`.`programas` (`id_programas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_aprendiz_Usuario1`
    FOREIGN KEY (`Usuario_id_usuario`)
    REFERENCES `mydb`.`Usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_aprendiz_jornada1`
    FOREIGN KEY (`jornada_id_jornada`)
    REFERENCES `mydb`.`jornada` (`id_jornada`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

CREATE INDEX `fk_aprendiz_programas1` ON `mydb`.`aprendiz` (`programas_id_programas` ASC) VISIBLE;

CREATE INDEX `fk_aprendiz_Usuario1_idx` ON `mydb`.`aprendiz` (`Usuario_id_usuario` ASC) VISIBLE;

CREATE INDEX `fk_aprendiz_jornada1_idx` ON `mydb`.`aprendiz` (`jornada_id_jornada` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`rol`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`rol` ;

CREATE TABLE IF NOT EXISTS `mydb`.`rol` (
  `id_rol` INT NOT NULL,
  `nombre_rol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_rol`));


-- -----------------------------------------------------
-- Table `mydb`.`user_rol`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`user_rol` ;

CREATE TABLE IF NOT EXISTS `mydb`.`user_rol` (
  `id_user_rol` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `id_rol` INT NOT NULL,
  PRIMARY KEY (`id_user_rol`),
  CONSTRAINT `fk_user_rol_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `mydb`.`Usuario` (`id_usuario`),
  CONSTRAINT `fk_user_rol_rol`
    FOREIGN KEY (`id_rol`)
    REFERENCES `mydb`.`rol` (`id_rol`));

CREATE INDEX `fk_user_rol_usuario` ON `mydb`.`user_rol` (`id_usuario` ASC) VISIBLE;

CREATE INDEX `fk_user_rol_rol` ON `mydb`.`user_rol` (`id_rol` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`ambiente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ambiente` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ambiente` (
  `id_ambiente` INT NOT NULL,
  `num_ambiente` SMALLINT NOT NULL,
  `capacidad` SMALLINT NOT NULL,
  `tipo_ambiente` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(30) NOT NULL,
  `coordinacion_id` INT NOT NULL,
  PRIMARY KEY (`id_ambiente`),
  CONSTRAINT `fk_ambiente_coordinacion`
    FOREIGN KEY (`coordinacion_id`)
    REFERENCES `mydb`.`coordinacion` (`id_coordinacion`));

CREATE INDEX `fk_ambiente_coordinacion` ON `mydb`.`ambiente` (`coordinacion_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`tipo_incidente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tipo_incidente` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tipo_incidente` (
  `id_tipo_inc` INT NOT NULL,
  `tipo_incidente` VARCHAR(45) NOT NULL,
  `observacion_inc` TEXT NOT NULL,
  PRIMARY KEY (`id_tipo_inc`));


-- -----------------------------------------------------
-- Table `mydb`.`registro_incidente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`registro_incidente` ;

CREATE TABLE IF NOT EXISTS `mydb`.`registro_incidente` (
  `id_incidente` INT NOT NULL AUTO_INCREMENT,
  `descripcion` TEXT NULL DEFAULT NULL,
  `fecha_incidente` DATE NOT NULL,
  `hora_incidente` TIME NOT NULL,
  `ambiente_id` INT NOT NULL,
  `tipo_inc_id` INT NOT NULL,
  PRIMARY KEY (`id_incidente`),
  CONSTRAINT `fk_registro_incidente_ambiente`
    FOREIGN KEY (`ambiente_id`)
    REFERENCES `mydb`.`ambiente` (`id_ambiente`),
  CONSTRAINT `fk_registro_incidente_tipo_inc`
    FOREIGN KEY (`tipo_inc_id`)
    REFERENCES `mydb`.`tipo_incidente` (`id_tipo_inc`));

CREATE INDEX `fk_registro_incidente_ambiente` ON `mydb`.`registro_incidente` (`ambiente_id` ASC) VISIBLE;

CREATE INDEX `fk_registro_incidente_tipo_inc` ON `mydb`.`registro_incidente` (`tipo_inc_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`tipo_recurso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tipo_recurso` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tipo_recurso` (
  `id_tipo_recurso` INT NOT NULL,
  `recurso_tipo` VARCHAR(45) NOT NULL,
  `descripcion_tipo` VARCHAR(60) NULL,
  PRIMARY KEY (`id_tipo_recurso`));


-- -----------------------------------------------------
-- Table `mydb`.`recursos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`recursos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`recursos` (
  `id_recurso` INT NOT NULL AUTO_INCREMENT,
  `serial_recurso` VARCHAR(100) NOT NULL,
  `num_recurso` TINYINT NOT NULL,
  `nombre_recurso` VARCHAR(60) NOT NULL,
  `tipo_recurso` INT NOT NULL,
  `observacion` TEXT NULL,
  `ambiente_id` INT NOT NULL,
  PRIMARY KEY (`id_recurso`),
  CONSTRAINT `fk_recursos_tipo_recurso`
    FOREIGN KEY (`tipo_recurso`)
    REFERENCES `mydb`.`tipo_recurso` (`id_tipo_recurso`),
  CONSTRAINT `fk_recursos_ambiente`
    FOREIGN KEY (`ambiente_id`)
    REFERENCES `mydb`.`ambiente` (`id_ambiente`));

CREATE INDEX `fk_recursos_tipo_recurso` ON `mydb`.`recursos` (`tipo_recurso` ASC) VISIBLE;

CREATE INDEX `fk_recursos_ambiente` ON `mydb`.`recursos` (`ambiente_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`registro_minuta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`registro_minuta` ;

CREATE TABLE IF NOT EXISTS `mydb`.`registro_minuta` (
  `id_minuta` INT NOT NULL AUTO_INCREMENT,
  `fecha_hora_recibo` DATETIME NOT NULL,
  `fecha_hora_entrega` DATETIME NOT NULL,
  `novedad` TEXT NULL,
  `responsable` VARCHAR(250) NOT NULL,
  `descripcion_min` TEXT NULL DEFAULT NULL,
  `ambiente_id` INT NOT NULL,
  `Usuario_id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_minuta`),
  CONSTRAINT `fk_registro_minuta_usuario`
    FOREIGN KEY (`Usuario_id_usuario`)
    REFERENCES `mydb`.`Usuario` (`id_usuario`),
  CONSTRAINT `fk_registro_minuta_ambiente`
    FOREIGN KEY (`ambiente_id`)
    REFERENCES `mydb`.`ambiente` (`id_ambiente`));

CREATE INDEX `fk_registro_minuta_usuario` ON `mydb`.`registro_minuta` (`Usuario_id_usuario` ASC) VISIBLE;

CREATE INDEX `fk_registro_minuta_ambiente` ON `mydb`.`registro_minuta` (`ambiente_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`registro_asistencia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`registro_asistencia` ;

CREATE TABLE IF NOT EXISTS `mydb`.`registro_asistencia` (
  `id_asistencia` INT NOT NULL AUTO_INCREMENT,
  `fecha_asistencia` DATE NOT NULL,
  `estado_asistencia` ENUM('E', 'F', 'I') NOT NULL,
  `jornada_id` INT NOT NULL,
  `aprendiz_Usuario_id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_asistencia`),
  CONSTRAINT `fk_registro_asistencia_jornada`
    FOREIGN KEY (`jornada_id`)
    REFERENCES `mydb`.`jornada` (`id_jornada`),
  CONSTRAINT `fk_registro_asistencia_aprendiz1`
    FOREIGN KEY (`aprendiz_Usuario_id_usuario`)
    REFERENCES `mydb`.`aprendiz` (`Usuario_id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

CREATE INDEX `fk_registro_asistencia_jornada` ON `mydb`.`registro_asistencia` (`jornada_id` ASC) VISIBLE;

CREATE INDEX `fk_registro_asistencia_aprendiz1_idx` ON `mydb`.`registro_asistencia` (`aprendiz_Usuario_id_usuario` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`alertas_inasistencia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`alertas_inasistencia` ;

CREATE TABLE IF NOT EXISTS `mydb`.`alertas_inasistencia` (
  `id_alerta` INT NULL DEFAULT NULL,
  `aprendiz_id` INT NOT NULL,
  `cantidad_fallas` INT NOT NULL,
  `fecha_alerta` DATETIME NOT NULL,
  `mensaje` TEXT NOT NULL,
  `coordinacion_id` INT NOT NULL,
  PRIMARY KEY (`id_alerta`),
  CONSTRAINT `fk_alertas_inasistencia_coordinacion`
    FOREIGN KEY (`coordinacion_id`)
    REFERENCES `mydb`.`coordinacion` (`id_coordinacion`));

CREATE INDEX `fk_alertas_inasistencia_coordinacion` ON `mydb`.`alertas_inasistencia` (`coordinacion_id` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
