# Generated by Django 6.0.2 on 2026-06-15 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admin',
            options={'managed': False},
        ),
    ]
